import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

function requireEnv(key: string): string {
  const val = process.env[key];
  if (!val) throw new Error(`Missing required env var: ${key}`);
  return val;
}

function optionalEnv(key: string, fallback: string): string {
  return process.env[key] || fallback;
}

export const config = {
  ibm: {
    token: () => requireEnv('IBM_QUANTUM_TOKEN'),
  },
  solana: {
    keypairPath: () => requireEnv('SOLANA_KEYPAIR_PATH'),
    rpcUrl: optionalEnv('SOLANA_RPC_URL', 'https://api.mainnet-beta.solana.com'),
  },
  token: {
    devBuySol: parseFloat(optionalEnv('DEV_BUY_SOL', '0.0001')),
    circuitStyle: optionalEnv('CIRCUIT_STYLE', 'soft') as 'soft' | 'hard' | 'harmonic',
    shots: parseInt(optionalEnv('SHOTS', '8192'), 10),
    website: optionalEnv('TOKEN_WEBSITE', ''),
    description: optionalEnv('TOKEN_DESCRIPTION',
      "This token's name and artwork were generated by a 20-qubit quantum circuit executed on a real IBM Quantum Processing Unit — not a chatbot wrapper, not a simulator, not an AI agent with a quantum API bolted on. The measurement results from 8,192 shots on physical superconducting qubits determined the name, and the token deployment transaction was triggered directly by the quantum job pipeline. Verify: query the IBM Job ID below at quantum.cloud.ibm.com, pull the measurement results, take the most-measured 20-bit string, split into four 5-bit groups, map 0-25 to A-Z — you'll get this token's name."
    ),
  },
};
